routes/web.php
<?php

use App\Http\Controllers\BrandController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SizeController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WishlistController;
use Illuminate\Support\Facades\Route;

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/product-details/{product}', [FrontendController::class, 'singleProduct'])->name('product-details');
Route::get('/shop/{sub_category}', [FrontendController::class, 'show'])->name('sub-categories.shop');
Route::get('/categories-show.shop/{category}', [FrontendController::class, 'allshow'])->name('categories-show.shop');
Route::get('/sub-categories-show.shop/{sub_category}', [FrontendController::class, 'subshow'])->name('sub-categories-show.shop');
Route::get('/category-filter', [FrontendController::class, 'filter'])->name('category-filter');

//cart
Route::post('add-to-cart', [CartController::class, 'addToCart']);
Route::post('delete-cart-item', [CartController::class, 'deleteProduct']);
Route::post('update-cart', [CartController::class, 'updateCart']);

//wishlist
Route::post('add-to-wishlist', [WishlistController::class, 'addToWishlist']);
Route::post('delete-wishlist-item', [WishlistController::class, 'deleteWishlist']);

Route::middleware(['auth','web'])->group(function () {
    //frontend route start
    Route::get('/view-cart', [CartController::class, 'viewCart'])->name('view.cart');
    Route::get('/view-wish', [WishlistController::class, 'viewWishlist'])->name('view.wishlist');
    Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout');
    Route::post('/place-order', [CheckoutController::class, 'placeOrder'])->name('placeOrder');
    Route::get('/my-order', [FrontendController::class, 'myOrder'])->name('my-order');
    Route::get('/view-order/{id}', [FrontendController::class, 'viewOrder'])->name('view-order');
    Route::get('/user-profile.edit', [FrontendController::class, 'edit'])->name('profile.edit');
    Route::get('/user/profile.edit', [ProfileController::class, 'edit'])->name('user.profile.edit');
    //comment
    Route::post('commnets/{id}', [CommentController::class, 'store'])->name('comment.store');
    //frontend route End
    
    
    //crud route start

    Route::get('/dashboard', function () {
        return view('backend.dashboard');
    })->name('dashboard');

    //orders crud
    Route::get('/orders', [OrderController::class, 'index'])->name('orders.index');
    Route::get('/orders/{id}', [OrderController::class, 'show'])->name('orders.show');
    Route::post('/orders/update/{id}', [OrderController::class, 'update'])->name('orders.update');
    Route::get('/orders-history', [OrderController::class, 'history'])->name('orders.history');
    Route::get('/orders-cancel', [OrderController::class, 'cancel'])->name('orders.cancel');
    Route::get('/orders.remove/{id}', [OrderController::class, 'remove'])->name('orders.remove');



    //roles crud
    Route::get('/roles', [RoleController::class, 'index'])->name('roles.index');
    Route::get('/roles/{role}', [RoleController::class, 'show'])->name('roles.show');

    //notification
    Route::get('/notifications/{notification}', [NotificationController::class, 'show'])->name('notifications.show');

    //users crud
    Route::resource('users', UserController::class)->except(['create', 'store']);
    Route::get('/users-trash', [UserController::class, 'trash'])->name('users.trash');
    Route::get('/users-trash/{user}', [UserController::class, 'restore'])->name('users.restore');
    Route::get('/users-trash/{user}/delete', [UserController::class, 'delete'])->name('users.delete');
    Route::get('/users-excel', [UserController::class, 'excel'])->name('users.excel');
    Route::get('/users-pdf', [UserController::class, 'pdf'])->name('users.pdf');
    Route::get('/user/profile.edit', [ProfileController::class, 'edit'])->name('user.profile.edit');
    Route::patch('/user/profile.update', [ProfileController::class, 'update'])->name('user.profile.update');

    //category crud
    Route::get('/categories-trash', [CategoryController::class, 'trash'])->name('categories.trash');
    Route::get('/categories-trash/{category}', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::get('/categories-trash/{category}/delete', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::get('/categories-excel', [CategoryController::class, 'excel'])->name('categories.excel');
    Route::get('/categories-pdf', [CategoryController::class, 'pdf'])->name('categories.pdf');
    Route::resource('categories', CategoryController::class);

    //sub category crud
    Route::get('/sub-categories-trash', [SubCategoryController::class, 'trash'])->name('sub-categories.trash');
    Route::get('/sub-categories-trash/{sub_category}', [SubCategoryController::class, 'restore'])->name('sub-categories.restore');
    Route::get('/sub-categories-trash/{sub_category}/delete', [SubCategoryController::class, 'delete'])->name('sub-categories.delete');
    Route::resource('sub-categories', SubCategoryController::class);

    //product crud
    Route::get('/products-trash', [ProductController::class, 'trash'])->name('products.trash');
    Route::get('/products-trash/{product}', [ProductController::class, 'restore'])->name('products.restore');
    Route::get('/products-trash/{product}/delete', [ProductController::class, 'delete'])->name('products.delete');
    Route::get('/products-excel', [ProductController::class, 'excel'])->name('products.excel');
    Route::get('/products-pdf', [ProductController::class, 'pdf'])->name('products.pdf');
    Route::resource('products', ProductController::class);

    //tags crud
    Route::resource('tags', TagController::class);
    Route::get('/tags-trash', [TagController::class, 'trash'])->name('tags.trash');
    Route::get('/tags-trash/{tag}', [TagController::class, 'restore'])->name('tags.restore');
    Route::get('/tags-trash/{tag}/delete', [TagController::class, 'delete'])->name('tags.delete');
    Route::get('/tags-excel', [TagController::class, 'excel'])->name('tags.excel');
    Route::get('/tags-pdf', [TagController::class, 'pdf'])->name('tags.pdf');

    //sizes crud
    Route::resource('sizes', SizeController::class);
    Route::get('/sizes-trash', [SizeController::class, 'trash'])->name('sizes.trash');
    Route::get('/sizes-trash/{size}', [SizeController::class, 'restore'])->name('sizes.restore');
    Route::get('/sizes-trash/{size}/delete', [SizeController::class, 'delete'])->name('sizes.delete');
    Route::get('/sizes-excel', [SizeController::class, 'excel'])->name('sizes.excel');
    Route::get('/sizes-pdf', [SizeController::class, 'pdf'])->name('sizes.pdf');

    //colors crud
    Route::resource('colors', ColorController::class);
    Route::get('/colors-trash', [ColorController::class, 'trash'])->name('colors.trash');
    Route::get('/colors-trash/{color}', [ColorController::class, 'restore'])->name('colors.restore');
    Route::get('/colors-trash/{color}/delete', [ColorController::class, 'delete'])->name('colors.delete');
    Route::get('/colors-excel', [ColorController::class, 'excel'])->name('colors.excel');
    Route::get('/colors-pdf', [ColorController::class, 'pdf'])->name('colors.pdf');

    //brands crud
    Route::resource('brands', BrandController::class);
    Route::get('/brands-trash', [BrandController::class, 'trash'])->name('brands.trash');
    Route::get('/brands-trash/{brand}', [BrandController::class, 'restore'])->name('brands.restore');
    Route::get('/brands-trash/{brand}/delete', [BrandController::class, 'delete'])->name('brands.delete');
    Route::get('/brands-excel', [BrandController::class, 'excel'])->name('brands.excel');
    Route::get('/brands-pdf', [BrandController::class, 'pdf'])->name('brands.pdf');

    //crud route end
});

require __DIR__ . '/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class,'category_id');
    }

    public function subcategory()
    {
        return $this->belongsTo(SubCategory::class,'subcategory_id');
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function sizes()
    {
        return $this->belongsToMany(Size::class);
    }

    public function colors()
    {
        return $this->belongsToMany(Color::class);
    }

    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }
}

resources/views/backend/products/create.blade.php
<x-backend.layouts.master>
    <x-slot name="page_title">
        Products
    </x-slot>

    <x-slot name="breadcrumb">
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader">
                Products
            </x-slot>
            <x-slot name="add">
                
            </x-slot>
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{ route('products.index') }}">Products</a></li>
            <li class="breadcrumb-item active">Create</li>
        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header ">
            
            <div class="d-flex justify-content-between">
                <span><i class="fas fa-table me-1"></i>Products</span>
                <span>
                    <a class="btn btn-primary text-left" href="{{ Route('products.index') }}" role="button">List</a>
                </span>
            </div>
        </div>
        <div class="card-body">
            <x-backend.layouts.elements.errors :errors="$errors"/>
            <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="row mb-3">
                    <div class="col-md-6 mb-2">
                        <x-backend.form.input name="name" :value="old('name')"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.input name="price" type="number" :value="old('price')"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.input name="discount" type="number" :value="old('discount')"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.input name="quantity" type="number" :value="old('quantity')"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.select name="category_id" label="Category" :option="$categories"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.select name="subcategory_id" label="Sub Category" :option="$subcategories"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.select name="brand_id" label="Brand" :option="$brands"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <p>Tag:</p>
                        @foreach ($tags as $key=>$value)
                        <x-backend.form.checkbox name="tag_id[]" value="{{ $key }}" label="{{ $value }}"
                        select="{{ in_array($key, old('tag_id')??[]) ? 'checked':'' }}"/>
                        @endforeach
                    </div>
                    <div class="col-md-6 mb-2">
                        <p>Size:</p>
                        @foreach ($sizes as $key=>$value)
                        <x-backend.form.checkbox name="size_id[]" value="{{ $key }}" label="{{ $value }}"
                        select="{{ in_array($key, old('size_id')??[]) ? 'checked':'' }}"/>
                        @endforeach                    
                    </div>
                    <div class="col-md-6 mb-2">
                        <p>Color:</p>
                        @foreach ($colors as $key=>$value)
                        <x-backend.form.checkbox name="color_id[]" value="{{ $key }}" label="{{ $value }}"
                        select="{{ in_array($key, old('color_id')??[]) ? 'checked':'' }}"/>
                        @endforeach                    
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.input name="sku" :value="old('sku')"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.textarea name="short_description">
                            {{ old('short_description') }}
                        </x-backend.form.textarea>
                    </div>
                    <div class="col-md-12 mb-2">
                        <x-backend.form.textarea name="long_description">
                            {{ old('long_description') }}
                        </x-backend.form.textarea>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.input name="image1" type="file"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.input name="image2" type="file"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.input name="image3" type="file"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.input name="image4" type="file"/>
                    </div>
                    {{-- <div class="col-md-6 mb-2">
                        <label for="our_feature" class="form-label">Our Feature</label><br>
                        <select name="our_feature"  class="form-select" style="height: 38px; border:1px solid 	#DCDCDC; border-radius:5px; width:100%;">
                            <option value="">Choose... </option>
                            <option value="1" {{ old('our_feature') == '1' ? 'selected': '' }}>Our Feature Product</option>
                            @error('our_feature')
                            <span class="sm text-danger">{{ $message }}</span>
                        @enderror
                        </select>
                    </div> --}}

                    @push('script')
                    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

                    <script>
                        tinymce.init({
                        selector: '#long_description'
                        });
                    </script>
                    @endpush

                </div>
                <div class="mt-4 mb-0">
                    <div class="d-grid"><button class="btn btn-primary btn-block" type="submit">Save</button></div>
                </div>
            </form>
        </div>
    </div>

</x-backend.layouts.master>

resources/views/backend/products/edit.blade.php
<x-backend.layouts.master>


    <x-slot name="page_title">
        Products
    </x-slot>
    <x-slot name="breadcrumb">
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader">
                Products
            </x-slot>
            <x-slot name="add">  
            </x-slot>
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{ Route('products.index') }}">Products</a></li>
            <li class="breadcrumb-item active">Edit</li>
        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header ">
            <div class="d-flex justify-content-between">
                <span><i class="fas fa-table me-1"></i>Products</span>
                <span>
                    <a class="btn btn-primary text-left" href="{{ Route('products.index') }}" role="button">List</a>
                </span>
            </div>
        </div>
        <div class="card-body">
            <x-backend.layouts.elements.errors :errors="$errors"/>
            <form action="{{ route('products.update', ['product' => $product->id]) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('patch')
                <div class="row mb-3">
                    <div class="col-md-6">
                        <x-backend.form.input name="name" :value="old('name',$product->name)"/>
                    </div>
                    <div class="col-md-6">
                        <x-backend.form.input name="price" :value="old('price',$product->price)"/>
                    </div>
                    <div class="col-md-6">
                        <x-backend.form.input name="discount" :value="old('discount',$product->discount)"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.input name="quantity" type="number" :value="old('quantity',$product->quantity)"/>
                    </div>
                    <div class="col-md-6">
                        <x-backend.form.select name="category_id" label="Category" :option="$categories" select="{{ $product->category_id }}"/>
                    </div>
                    <div class="col-md-6">
                        <x-backend.form.select name="subcategory_id" label="Sub Category" :option="$subcategories" select="{{ $product->subcategory_id }}"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.select name="brand_id" label="Brand" :option="$brands" select="{{ $product->brand_id }}"/>
                    </div>
                    <div class="col-md-6 mt-2">
                        <p>Tags:</p>
                        @foreach ($tags as $key=>$value)
                        <x-backend.form.checkbox name="tag_id[]" value="{{ $key }}" label="{{ $value }}" 
                            select="{{ in_array($key, old('tag_id')??$selectedTags) ? 'checked':'' }}"/>
                        @endforeach
                    </div>
                    <div class="col-md-6 mb-2">
                        <p>Sizes:</p>
                        @foreach ($sizes as $key=>$value)
                        <x-backend.form.checkbox name="size_id[]" 
                            value="{{ $key }}" label="{{ $value }}"
                            select="{{ in_array($key, old('size_id')??$selectedSizes) ? 'checked':'' }}"/>
                        @endforeach                     
                    </div>
                    <div class="col-md-6 mb-2">
                        <p>Colors:</p>
                        @foreach ($colors as $key=>$value)
                        <x-backend.form.checkbox name="color_id[]" value="{{ $key }}" label="{{ $value }}" 
                            select="{{ in_array($key, old('color_id')??$selectedColors) ? 'checked':'' }}"/>
                        @endforeach                    
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.input name="sku" :value="old('sku',$product->sku)"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.textarea name="short_description">
                            {{ old('short_description',$product->short_description) }}
                        </x-backend.form.textarea>
                    </div>
                    <div class="col-md-12 mb-2">
                        <x-backend.form.textarea name="long_description">
                            {{ old('long_description',$product->long_description) }}
                        </x-backend.form.textarea>
                    </div>
                    <div class="col-md-6">
                        <x-backend.form.input name="image1" type="file"/>
                    </div>
                    <div class="col-md-6">
                        <x-backend.form.input name="image2" type="file"/>
                    </div>
                    <div class="col-md-6">
                        <x-backend.form.input name="image3" type="file"/>
                    </div>
                    <div class="col-md-6">
                        <x-backend.form.input name="image4" type="file"/>
                    </div>
                    {{-- <div class="col-md-6 mb-2">
                        <label for="our_feature" class="form-label">Our Feature</label><br>
                        <select name="our_feature"  class="form-select" style="height: 38px; border:1px solid 	#DCDCDC; border-radius:5px; width:100%;">
                            <option value="">Choose... </option>
                            <option value="1" {{ old('our_feature',$product->featured) == '1' ? 'selected': '' }}>Our Feature Product</option>
                            @error('our_feature')
                            <span class="sm text-danger">{{ $message }}</span>
                        @enderror
                        </select>
                    </div> --}}
                
                </div>
                <div class="mt-4 mb-0">
                    <div class="d-grid"><button onclick="return confirm('Are you sure want to update ?')" class="btn btn-primary btn-block" type="submit">Update</button></div>
                </div>
            </form>
        </div>
    </div>

    @push('script')
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

    <script>
        tinymce.init({
          selector: '#long_description'
        });
      </script>
      @endpush

</x-backend.layouts.master>

resources/views/backend/products/index.blade.php
<x-backend.layouts.master>
    <x-slot name="page_title">
        Products
    </x-slot>

    <x-slot name="breadcrumb">
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader">
                Products
            </x-slot>
            <x-slot name="add">
            </x-slot>
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
            <li class="breadcrumb-item active">Products</li>
        </x-backend.layouts.elements.breadcrumb>
    </x-slot>
    
<div class="card mb-4">
    <div class="card-header ">
        <div class="d-flex justify-content-between">
            <span><i class="fas fa-table me-1"></i>Products</span>
            @canany(['admin','editor'])
                <span>
                    <a class="btn btn-sm btn-primary text-left" href="{{ Route('products.create') }}" role="button">Add</a>
                    <a class="btn btn-sm btn-danger text-left" href="{{ route('products.trash') }}" role="button">Trash</a>
                    <a class="btn btn-sm btn-info text-left" href="{{ route('products.excel') }}" role="button">Excel</a>
                    <a class="btn btn-sm btn-info text-left" href="{{ route('products.pdf') }}" role="button">Pdf</a>
                </span>
            @endcanany
        </div>
    </div>
    <div class="card-body">
        <div class="d-flex justify-content-end mb-1">
            <form action="{{ route('products.index') }}" method="GET">
                <select name="category" class="form-select " style="width:220px">
                    <option value=""  style="border: 1px solid #DCDCDC;">Select One</option>
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}"{{ $category->id==$req?'selected':'' }}>{{ $category->name }}</option>
                            @endforeach
                </select>
                <x-backend.form.button >
                    Submit
                  </x-backend.form.button>
            </form>
            <form action="{{ route('products.index') }}" method="GET">
                <x-backend.form.search name="search" placeholder="Search" style="width: 220px;"/>
            </form>
        </div>
        <x-backend.layouts.elements.message :message="session('message')"/>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>SL#</th>
                    <th>Sub Category Name</th>
                    <th>Our Feature Product</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $sl = 0;
                @endphp
                @foreach ($products as $product)
                    <tr>
                        <td>{{ ++$sl }}</td>
                        <td>{{ $product->subcategory->name }}</td>
                        <td>{{ $product->featured }}</td>
                        <td>{{ $product->name }}</td>
                        <td>{{ $product->price }}</td>
                        <td>
                            <a class="btn btn-sm btn-primary" href="{{ route('products.show', ['product'=>$product->id]) }}" role="button">Show</a>
                            @canany(['admin','editor'])
                                <a class="btn btn-sm btn-warning" href="{{ route('products.edit', ['product'=>$product->id]) }}" role="button">Edit</a>
                                <form style="display: inline;" action="{{ route('products.destroy', ['product'=>$product->id]) }}" method="POST">
                                    @csrf
                                    @method('delete')
                                    <button onclick="return confirm('Are you sure want to delete ?')" class="btn btn-sm btn-danger" type="submit">Delete</button>
                                </form>
                            @endcanany
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        {{ $products->links() }}
    </div>
</div>

</x-backend.layouts.master>

resources/views/backend/products/pdf.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <table class="table table-bordered container">
        <thead>
          <tr>
            <th>SL#</th>
            <th>Name</th>
            <th>Short Description</th>
            <th>Price</th>
          </tr>
        </thead>
        <tbody>
            @php
            $sl = 0;
            @endphp
            @foreach ($products as $product)
            <tr>
                <td>{{ ++$sl }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ $product->short_description }}</td>
                <td>{{ $product->price }}</td>
            </tr>
            @endforeach
        </tbody>
      </table>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

resources/views/backend/products/show.blade.php
<x-backend.layouts.master>
    <x-slot name="page_title">
        Products
    </x-slot>

    <x-slot name="breadcrumb">
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader">
                Products
            </x-slot>
            <x-slot name="add">
            </x-slot>
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{ route('products.index') }}">Products</a></li>
            <li class="breadcrumb-item active">Show</li>
        </x-backend.layouts.elements.breadcrumb>
    </x-slot>
    
<div class="card mb-4">
    <div class="card-header ">
        <div class="d-flex justify-content-between">
            <span><i class="fas fa-table me-1"></i>Products</span>
            <span>
                <a class="btn btn-primary text-left" href="{{ Route('products.index') }}" role="button">List</a>
            </span>
        </div>
    </div>
    <div class="card-body">
        <div class="container">
            <p>Product ID : {{ $product->id }}</p>
            <p>Name :{{ $product->name }}</p>
            <p>Short Description :{{ $product->short_description }}</p>
            <p>Long Description :{!! $product->long_description !!}</p>
            {{-- <p>Category Name:{{ $product->subcategory->category->name }}</p> --}}
            <p>Sub Category Name:{{ $product->subcategory->name }}</p>
            <p>Brand:{{ $product->brand->name ?? '' }}</p>
            <p>Price :{{ $product->price }}</p>
            <p>Quantity :{{ $product->quantity }}</p>
            <p>SKU :{{ $product->sku }}</p>
            <p>
                Tag : 
            @foreach ($product->tags as $tag)
            <tr>
                <td>{{ $loop->iteration }}:</td>
                <td>{{ $tag->title }}</td>
            </tr>
            @endforeach
            </p>
            <p>
                Size : 
            @foreach ($product->sizes as $size)
            <tr>
                <td>{{ $loop->iteration }}:</td>
                <td>{{ $size->title }}</td>
            </tr>
            @endforeach
            </p>
            <p>
                Color : 
            @foreach ($product->colors as $color)
            <tr>
                <td>{{ $loop->iteration }}:</td>
                <td>{{ $color->name }}</td>
            </tr>
            @endforeach
            </p>
            <p>Image1 :<img src="{{ asset('storage/images/products/'.$product->image1) }}" alt="" style="width: 100px; height:100px"></p>
            <p>Image2 :<img src="{{ asset('storage/images/products/'.$product->image2) }}" alt="" style="width: 100px; height:100px"></p>
            <p>Image3 :<img src="{{ asset('storage/images/products/'.$product->image3) }}" alt="" style="width: 100px; height:100px"></p>
            <p>image4 :<img src="{{ asset('storage/images/products/'.$product->image4) }}" alt="" style="width: 100px; height:100px"></p>            
        </div>
    </div>
</div>

</x-backend.layouts.master>