routes/web.php
<?php

use App\Http\Controllers\BrandController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SizeController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WishlistController;
use Illuminate\Support\Facades\Route;

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/product-details/{product}', [FrontendController::class, 'singleProduct'])->name('product-details');
Route::get('/shop/{sub_category}', [FrontendController::class, 'show'])->name('sub-categories.shop');
Route::get('/categories-show.shop/{category}', [FrontendController::class, 'allshow'])->name('categories-show.shop');
Route::get('/sub-categories-show.shop/{sub_category}', [FrontendController::class, 'subshow'])->name('sub-categories-show.shop');
Route::get('/category-filter', [FrontendController::class, 'filter'])->name('category-filter');

//cart
Route::post('add-to-cart', [CartController::class, 'addToCart']);
Route::post('delete-cart-item', [CartController::class, 'deleteProduct']);
Route::post('update-cart', [CartController::class, 'updateCart']);

//wishlist
Route::post('add-to-wishlist', [WishlistController::class, 'addToWishlist']);
Route::post('delete-wishlist-item', [WishlistController::class, 'deleteWishlist']);

Route::middleware(['auth','web'])->group(function () {
    //frontend route start
    Route::get('/view-cart', [CartController::class, 'viewCart'])->name('view.cart');
    Route::get('/view-wish', [WishlistController::class, 'viewWishlist'])->name('view.wishlist');
    Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout');
    Route::post('/place-order', [CheckoutController::class, 'placeOrder'])->name('placeOrder');
    Route::get('/my-order', [FrontendController::class, 'myOrder'])->name('my-order');
    Route::get('/view-order/{id}', [FrontendController::class, 'viewOrder'])->name('view-order');
    Route::get('/user-profile.edit', [FrontendController::class, 'edit'])->name('profile.edit');
    Route::get('/user/profile.edit', [ProfileController::class, 'edit'])->name('user.profile.edit');
    //comment
    Route::post('commnets/{id}', [CommentController::class, 'store'])->name('comment.store');
    //frontend route End
    
    
    //crud route start

    Route::get('/dashboard', function () {
        return view('backend.dashboard');
    })->name('dashboard');

    //orders crud
    Route::get('/orders', [OrderController::class, 'index'])->name('orders.index');
    Route::get('/orders/{id}', [OrderController::class, 'show'])->name('orders.show');
    Route::post('/orders/update/{id}', [OrderController::class, 'update'])->name('orders.update');
    Route::get('/orders-history', [OrderController::class, 'history'])->name('orders.history');
    Route::get('/orders-cancel', [OrderController::class, 'cancel'])->name('orders.cancel');
    Route::get('/orders.remove/{id}', [OrderController::class, 'remove'])->name('orders.remove');



    //roles crud
    Route::get('/roles', [RoleController::class, 'index'])->name('roles.index');
    Route::get('/roles/{role}', [RoleController::class, 'show'])->name('roles.show');

    //notification
    Route::get('/notifications/{notification}', [NotificationController::class, 'show'])->name('notifications.show');

    //users crud
    Route::resource('users', UserController::class)->except(['create', 'store']);
    Route::get('/users-trash', [UserController::class, 'trash'])->name('users.trash');
    Route::get('/users-trash/{user}', [UserController::class, 'restore'])->name('users.restore');
    Route::get('/users-trash/{user}/delete', [UserController::class, 'delete'])->name('users.delete');
    Route::get('/users-excel', [UserController::class, 'excel'])->name('users.excel');
    Route::get('/users-pdf', [UserController::class, 'pdf'])->name('users.pdf');
    Route::get('/user/profile.edit', [ProfileController::class, 'edit'])->name('user.profile.edit');
    Route::patch('/user/profile.update', [ProfileController::class, 'update'])->name('user.profile.update');

    //category crud
    Route::get('/categories-trash', [CategoryController::class, 'trash'])->name('categories.trash');
    Route::get('/categories-trash/{category}', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::get('/categories-trash/{category}/delete', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::get('/categories-excel', [CategoryController::class, 'excel'])->name('categories.excel');
    Route::get('/categories-pdf', [CategoryController::class, 'pdf'])->name('categories.pdf');
    Route::resource('categories', CategoryController::class);

    //sub category crud
    Route::get('/sub-categories-trash', [SubCategoryController::class, 'trash'])->name('sub-categories.trash');
    Route::get('/sub-categories-trash/{sub_category}', [SubCategoryController::class, 'restore'])->name('sub-categories.restore');
    Route::get('/sub-categories-trash/{sub_category}/delete', [SubCategoryController::class, 'delete'])->name('sub-categories.delete');
    Route::resource('sub-categories', SubCategoryController::class);

    //product crud
    Route::get('/products-trash', [ProductController::class, 'trash'])->name('products.trash');
    Route::get('/products-trash/{product}', [ProductController::class, 'restore'])->name('products.restore');
    Route::get('/products-trash/{product}/delete', [ProductController::class, 'delete'])->name('products.delete');
    Route::get('/products-excel', [ProductController::class, 'excel'])->name('products.excel');
    Route::get('/products-pdf', [ProductController::class, 'pdf'])->name('products.pdf');
    Route::resource('products', ProductController::class);

    //tags crud
    Route::resource('tags', TagController::class);
    Route::get('/tags-trash', [TagController::class, 'trash'])->name('tags.trash');
    Route::get('/tags-trash/{tag}', [TagController::class, 'restore'])->name('tags.restore');
    Route::get('/tags-trash/{tag}/delete', [TagController::class, 'delete'])->name('tags.delete');
    Route::get('/tags-excel', [TagController::class, 'excel'])->name('tags.excel');
    Route::get('/tags-pdf', [TagController::class, 'pdf'])->name('tags.pdf');

    //sizes crud
    Route::resource('sizes', SizeController::class);
    Route::get('/sizes-trash', [SizeController::class, 'trash'])->name('sizes.trash');
    Route::get('/sizes-trash/{size}', [SizeController::class, 'restore'])->name('sizes.restore');
    Route::get('/sizes-trash/{size}/delete', [SizeController::class, 'delete'])->name('sizes.delete');
    Route::get('/sizes-excel', [SizeController::class, 'excel'])->name('sizes.excel');
    Route::get('/sizes-pdf', [SizeController::class, 'pdf'])->name('sizes.pdf');

    //colors crud
    Route::resource('colors', ColorController::class);
    Route::get('/colors-trash', [ColorController::class, 'trash'])->name('colors.trash');
    Route::get('/colors-trash/{color}', [ColorController::class, 'restore'])->name('colors.restore');
    Route::get('/colors-trash/{color}/delete', [ColorController::class, 'delete'])->name('colors.delete');
    Route::get('/colors-excel', [ColorController::class, 'excel'])->name('colors.excel');
    Route::get('/colors-pdf', [ColorController::class, 'pdf'])->name('colors.pdf');

    //brands crud
    Route::resource('brands', BrandController::class);
    Route::get('/brands-trash', [BrandController::class, 'trash'])->name('brands.trash');
    Route::get('/brands-trash/{brand}', [BrandController::class, 'restore'])->name('brands.restore');
    Route::get('/brands-trash/{brand}/delete', [BrandController::class, 'delete'])->name('brands.delete');
    Route::get('/brands-excel', [BrandController::class, 'excel'])->name('brands.excel');
    Route::get('/brands-pdf', [BrandController::class, 'pdf'])->name('brands.pdf');

    //crud route end
});

require __DIR__ . '/auth.php';

app/Models/SubCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class SubCategory extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $guarded = [];

    public function categories()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function products()
    {
        return $this->hasMany(Product::class, 'subcategory_id');
    }
}

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Product;
use App\Models\SubCategory;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;

class SubCategoryController extends Controller
{
    public function index()
    {
        try{
            $categoryCollection = SubCategory::latest();
            if(request('search')){
                $subcategory = $categoryCollection
                                ->where('name','like', '%'.request('search').'%');
            }
                $subcategory = $categoryCollection->paginate(5);
                return view('backend.subcategories.index',[
                'subcategories' => $subcategory,
            ]);
            
        }catch(QueryException $e){
            echo $e->getMessage();
        }
    }

    public function create()
    {
        $categories = Category::orderBY('name','asc')
                            ->pluck('name','id')
                            ->toArray();
        return view('backend.subcategories.create', [
            'categories' => $categories
        ]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:sub_categories,name'
        ]);

        try{
            SubCategory::create([
                'category_id' => $request->category,
                'name' => $request->name,
            ]);
            return redirect()->route('sub-categories.index')->withMessage('Task was successful!');
        }catch(QueryException $e){
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    public function show($subcategoryId)
    {
        $products = Product::where('subcategory_id', $subcategoryId)->get();
        return view('backend.subcategories.show', compact('products'));
    }

    public function edit($subcategoryId)
    {
        $categories = Category::orderBY('name','asc')
                            ->pluck('name','id')
                            ->toArray();
        $subcategory = SubCategory::findOrFail($subcategoryId);
        return view('backend.subcategories.edit',[
            'categories' =>$categories,
            'subcategory' => $subcategory
        ]);
    }

    public function update(Request $request ,$subcategoryId)
    {
        $request->validate([
            'name' => 'required',
        ]);

        $subcategory = SubCategory::findOrFail($subcategoryId);
        try{
            $subcategory->update([
                'category_id' => $request->category,
                'name' => $request->name,
            ]);
            return redirect()->route('sub-categories.index')->withMessage('Task was successfully Update!');
        }catch(QueryException $e){
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    public function destroy($subcategoryId)
    {
        $subcategory = SubCategory::findOrFail($subcategoryId);
        try{
            $subcategory->delete();
            return redirect()->route('sub-categories.index')->withMessage('Task was successfully Delete!');
        }catch(QueryException $e){
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    public function trash()
    {
        try{
            $subcategories = SubCategory::onlyTrashed()->get();
            return view('backend.subcategories.trash',[
                'subcategories' => $subcategories
            ]);
        }catch(QueryException $e){
            echo $e->getMessage();
        }
    }

    public function restore($id)
    {
        try{
            $category = SubCategory::onlyTrashed()->findOrFail($id);
            $category->restore();
            return redirect()->route('sub-categories.trash')->withMessage('Task was successfully Restore!');
        }catch(QueryException $e){
            echo $e->getMessage();
        }
    }

    public function delete($id)
    {
        try{
            $category = SubCategory::onlyTrashed()->findOrFail($id);
            $category->forceDelete();
            return redirect()->route('sub-categories.trash')->withMessage('Task was successfully Permanent Delete!');
        }catch(QueryException $e){
            echo $e->getMessage();
        }
    }
}

resources/views/backend/subcategories/create.blade.php
<x-backend.layouts.master>
    <x-slot name="page_title">
        Sub Categories
    </x-slot>

    <x-slot name="breadcrumb">
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader">
                Sub Categories
            </x-slot>
            <x-slot name="add">
                
            </x-slot>
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">Sub Categories</a></li>
            <li class="breadcrumb-item active">Create</li>
        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header ">
            
            <div class="d-flex justify-content-between">
                <span><i class="fas fa-table me-1"></i>Sub Categories</span>
                <span>
                    <a class="btn btn-primary text-left" href="{{ Route('sub-categories.index') }}" role="button">List</a>
                </span>
            </div>
        </div>
        <div class="card-body">
            <x-backend.layouts.elements.errors :errors="$errors"/>
            <form action="{{ route('sub-categories.store') }}" method="POST">
                @csrf
                <div class="row mb-3">
                    <div class="col-md-6 mb-2">
                        <x-backend.form.select name="category" label="Sub Category" :option="$categories"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.input name="name" :value="old('name')"/>
                    </div>
                </div>

                <div class="mt-4 mb-0">
                    <div class="d-grid"><button class="btn btn-primary btn-block" type="submit">Save</button></div>
                </div>
            </form>
        </div>
    </div>

</x-backend.layouts.master>

resources/views/backend/subcategories/edit.blade.php
<x-backend.layouts.master>
    <x-slot name="page_title">
        Sub Categories
    </x-slot>
    <x-slot name="breadcrumb">
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader">
                Sub Categories
            </x-slot>
            <x-slot name="add">  
            </x-slot>
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">Sub Categories</a></li>
            <li class="breadcrumb-item active">Edit</li>
        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header ">
            <div class="d-flex justify-content-between">
                <span><i class="fas fa-table me-1"></i>Sub Categories</span>
                <span>
                    <a class="btn btn-primary text-left" href="{{ Route('categories.index') }}" role="button">List</a>
                </span>
            </div>
        </div>
        <div class="card-body">
            <x-backend.layouts.elements.errors :errors="$errors"/>
            <form action="{{ route('sub-categories.update', ['sub_category' => $subcategory->id]) }}" method="POST">
                @csrf
                @method('patch')
                <div class="row mb-3">
                    <div class="col-md-6 mb-2">
                        <x-backend.form.select name="category" label="Sub Category" :option="$categories" select="{{ $subcategory->category_id }}"/>
                    </div>
                    <div class="col-md-6 mb-2">
                        <x-backend.form.input name="name" :value="old('name',$subcategory->name)"/>
                    </div>
                </div>

                <div class="mt-4 mb-0">
                    <div class="d-grid"><button onclick="return confirm('Are you sure want to update ?')" class="btn btn-primary btn-block" type="submit">Update</button></div>
                </div>
            </form>
        </div>
    </div>

</x-backend.layouts.master>

resources/views/backend/subcategories/index.blade.php
<x-backend.layouts.master>
    <x-slot name="page_title">
        Sub Categories
    </x-slot>

    <x-slot name="breadcrumb">
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader">
                Sub Categories
            </x-slot>
            <x-slot name="add">
            </x-slot>
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                <li class="breadcrumb-item active">Sub Categories</li>
        </x-backend.layouts.elements.breadcrumb>
    </x-slot>
    
<div class="card mb-4">
    <div class="card-header ">
        <div class="d-flex justify-content-between">
            <span><i class="fas fa-table me-1"></i>Sub Categories</span>
            @canany(['admin','editor'])
                <span>
                    <a class="btn btn-sm btn-primary text-left" href="{{ Route('sub-categories.create') }}" role="button">Add</a>
                    <a class="btn btn-sm btn-danger text-left" href="{{ route('sub-categories.trash') }}" role="button">Trash</a>
                    {{-- <a class="btn btn-sm btn-info text-left" href="{{ route('sub-categories.excel') }}" role="button">Excel</a>
                    <a class="btn btn-sm btn-info text-left" href="{{ route('sub-categories.pdf') }}" role="button">Pdf</a> --}}
                </span>
            @endcanany
        </div>
    </div>
    <div class="card-body">
        {{-- <form action="{{ route('categories.index') }}" method="GET">
            <x-backend.form.search name="search" placeholder="Search" style="width: 220px;"/>
        </form> --}}
        <x-backend.layouts.elements.message :message="session('message')"/>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>SL#</th>
                    <th>Category Name</th>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $sl = 0;
                @endphp
                @foreach ($subcategories as $subcategory)
                    <tr>
                        <td>{{ ++$sl }}</td>
                        <td>{{ $subcategory->categories->name }}</td>
                        <td>{{ $subcategory->name }}</td>
                        <td>
                            <a class="btn btn-sm btn-primary" href="{{ route('sub-categories.show', ['sub_category'=>$subcategory->id]) }}" role="button">Show</a>
                            @canany(['admin','editor'])
                                <a class="btn btn-sm btn-warning" href="{{ route('sub-categories.edit', ['sub_category'=>$subcategory->id]) }}" role="button">Edit</a>
                                <form style="display: inline;" action="{{ route('sub-categories.destroy', ['sub_category'=>$subcategory->id]) }}" method="POST">
                                    @csrf
                                    @method('delete')
                                    <button onclick="return confirm('Are you sure want to delete ?')" class="btn btn-sm btn-danger" type="submit">Delete</button>
                                </form>
                            @endcanany
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        {{ $subcategories->links() }}
    </div>
</div>

</x-backend.layouts.master>

resources/views/backend/subcategories/pdf.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <table class="table table-bordered container">
        <thead>
          <tr>
            <th>SL#</th>
            <th>Name</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
            @php
            $sl = 0;
            @endphp
            @foreach ($categories as $category)
            <tr>
                <td>{{ ++$sl }}</td>
                <td>{{ $category->name }}</td>
                <td>{{ $category->description }}</td>
            </tr>
            @endforeach
        </tbody>
      </table>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

resources/views/backend/subcategories/show.blade.php
<x-backend.layouts.master>
    <x-slot name="page_title">
        Sub Categories
    </x-slot>

    <x-slot name="breadcrumb">
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader">
                Sub Categories
            </x-slot>
            <x-slot name="add">
            </x-slot>
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">Sub Categories</a></li>
            <li class="breadcrumb-item active">Show</li>
        </x-backend.layouts.elements.breadcrumb>
    </x-slot>
    
<div class="card mb-4">
    <div class="card-header ">
        <div class="d-flex justify-content-between">
            <span><i class="fas fa-table me-1"></i>Sub Categories</span>
            <span>
                <a class="btn btn-primary text-left" href="{{ Route('sub-categories.index') }}" role="button">List</a>
            </span>
        </div>
    </div>
    <div class="card-body">
        <table class="table border">
            <thead>
                <tr>
                    <th>SL#</th>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Image</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($products as $product)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $product->name }}</td>
                    <td>{{ $product->price }}</td>
                    <td>{{ $product->quantity }}</td>
                    <td><img src="{{ asset('storage/images/products/'.$product->image1) }}" alt="" style="width: 100px; height:100px"></td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

</x-backend.layouts.master>

resources/views/backend/subcategories/trash.blade.php
<x-backend.layouts.master>
    <x-slot name="page_title">
        Sub Categories
    </x-slot>

    <x-slot name="breadcrumb">
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader">
                Sub Categories
            </x-slot>
            <x-slot name="add">
            </x-slot>
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('sub-categories.index') }}">Sub Categories</a></li>
                <li class="breadcrumb-item active">Trash</li>
        </x-backend.layouts.elements.breadcrumb>
    </x-slot>
    
<div class="card mb-4">
    <div class="card-header ">
        <div class="d-flex justify-content-between">
            <span><i class="fas fa-table me-1"></i>Sub Categories</span>
            <span>
                <a class="btn btn-primary text-left" href="{{ route('sub-categories.index') }}" role="button">List</a>
            </span>
        </div>
    </div>
    <div class="card-body">
        <x-backend.layouts.elements.message :message="session('message')"/>
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>SL#</th>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                    @php
                        $sl = 0;
                    @endphp
                    @foreach ($subcategories as $category)
                    <tr>
                        <td>{{ ++$sl }}</td>
                        <td>{{ $category->name }}</td>
                        <td>
                            <a onclick="return confirm('Are you sure want to restore ?')" class="btn btn-sm btn-primary mb-1" href="{{ route('sub-categories.restore', ['sub_category' => $category->id]) }}" role="button">Restore</a>
                            <a onclick="return confirm('Are you sure want to permanentdelete ?')" class="btn btn-sm btn-danger" href="{{ route('sub-categories.delete', ['sub_category' => $category->id]) }}" role="button">Permanent Delete</a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

</x-backend.layouts.master>